### ISSUE TITLE
defective image scaling/export

### ISSUE THREAD

**Issue by j0kaso** [arose/ngl#50] opened 2016-02-04 09:42 UTC
for image exports with scaling > 1 the resulting figure is wrongly composed (e.g. like a puzzle)

**Comment by arose** [comment] 2016-02-11 16:36
I can reproduce it (see attached image). It seems to be triggered by the antialias option and scale >= 2. At scale 1 or generally without antialias enabled is is ok for me.

![screenshot 3](https://cloud.githubusercontent.com/assets/272250/12982622/5b7c40cc-d09a-11e5-9da3-288c5481a527.png)

**Comment by j0kaso** [comment] 2016-02-12 08:54
I can produce also broken images without antialias for scaling > 4

**Comment by arose** [comment] 2016-04-09 01:36
fixed in dev branch

**Closed by arose** 2016-04-09 01:36 UTC
Labels: bug
