### ISSUE TITLE
Are label x-y-zCutoff parameters in angstroms?

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#484] opened 2018-03-01 18:39 UTC
Hi, Are label x-y-zCutoff parameters in angstroms?

**Comment by arose** [comment] 2018-03-04 01:05
is supposed to be in angstrom (or whatever the unit of your loaded data is)

**Comment by arose** [comment] 2018-03-04 01:05
otherwise closing as duplicate of #486

**Closed by arose** 2018-03-04 01:05 UTC
