### ISSUE TITLE
Ctrl+click picking atoms in multi-unit PDB picks the atoms in the other subunit

### ISSUE THREAD

**Issue by jaimergp** [arose/ngl#459] opened 2018-02-02 08:14 UTC
Hi, I was testing the current state of the TS2 branch in http://nglviewer.org/ts2 and opened PDB `3PK2` to fiddle with distance, angle and dihedral measurements.

I found out that if you pick atoms in one the ligands in this PDB, it selects the equivalent atoms in the other subunit. The screenshot attached lacks the mouse cursor: I was clicking on the aromatic ring on the left, but the selected atoms were those in the other subunit. I guess it has something to do with the atom names or something.

![captura de pantalla de 2018-02-02 09-09-58](https://user-images.githubusercontent.com/2559438/35723065-384adbc0-07f9-11e8-9fbf-05eca63b1c0c.png)

**Comment by fredludlow** [comment] 2018-02-02 11:00
I'm not sure how to fix this, but the issue is to do with asymmetric vs biological units, the AU is the monomer and the BU is the tetramer, so those are actually the same underlying atoms in the structure. 

A workaround in the meantime would be to use the biological unit file from the RCSB:
https://files.rcsb.org/download/3PK2.pdb1.gz

You also need to clear the `/0` selection on the top level to display all the models (each chain of the tetramer is stored in a different model in the biounit file)

**Comment by arose** [comment] 2018-02-02 18:03
Two aspects.

1) There is a bug, measurements should be shown for all rendered instances of a structure (as in the same atoms are rendered multiple times at different positions)
2) Measurements between two different instances of a structure can not be done currently, the workaround is, as @fredludlow described, to use a biological unit file from the PDB.

**Comment by arose** [comment] 2018-02-03 01:42
1) is fixed in ngl@2.0.0-dev.16, try here http://nglviewer.org/ts2/?load=rcsb://3PK2
2) can't be fixed for now

**Closed** 2018-02-26 06:34 UTC
Labels: bug, question
