### ISSUE TITLE
Surface calculation in IE11 not working when useWorker is true.

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#393] opened 2017-09-28 11:43 UTC
Hi, I was tryng to generate surface representation in IE11 and i finded that, for me, it doesn't work when useWorker is true. It generates an error like this:

SCRIPT5022: SecurityError 

at this line (from the minified version) 

var r = 0, i = 0, n = {}, o = {}, a = window.URL.createObjectURL(Wf.get(e)), s = new window.Worker(a);

**Comment by fredludlow** [comment] 2017-09-28 12:33
What specific version of IE11 do you have?
I can't reproduce it here (IE 11.0.9600.18792 Update 11.0.46), but googling suggests you're not alone:
https://stackoverflow.com/questions/30871817/security-error-on-ie11-when-using-worker

Also, are you serving the page from the file system/localhost/intranet/public web? (IE11 rules regarding whats allowed in different zones are, urm, somewhat opaque).

**Comment by giagitom** [comment] 2017-09-28 13:17
I'm using version 11.1715.14393.0 
I'm serving the file from the public web. The strange thing is that using the same version of IE11 [http://nglviewer.org/ngl/](http://nglviewer.org/ngl/) surface calculation works in any case (with/without useWorker on).  I don't understand if I am missing something or there is something different behind this.

**Comment by fredludlow** [comment] 2017-09-28 13:40
Maybe CORS related? (nglviewer.org site specifies Access-Control-Allow-Origin: *). 

Can you share your url that's not working?

**Comment by arose** [comment] 2017-09-30 03:23
it should work as the web worker code is generated at runtime and not loaded from anywhere. I kinda like the answer from Microsoft "Thank you for the feedback. This issue appears to have been fixed in Microsoft Edge. We're not presently working on feature bugs in Internet Explorer outside of security-related issues." (https://connect.microsoft.com/IE/feedback/details/801810/web-workers-from-blob-urls-in-ie-10-and-11). However if I can reproduce I still try to fix bugs for ie11.

**Comment by giagitom** [comment] 2017-10-02 09:00
Seems that I am unable to reproduce the error. Don't know what happened but for the moment it works. If I find the way to reproduce it I will let you know.

**Comment by arose** [comment] 2017-10-02 16:28
ok, please reopen then

**Closed by arose** 2017-10-02 16:28 UTC
Labels: question
